DefaultContentLanguage = "en"
disqusShortname = "stack"
hasCJKLanguage = true
languageCode = "en-us"
paginate = 5
theme = "stack"
title = "LoveSnowEx's Blog"
baseURL = "https://blog.lovesnowex.tk/"
googleAnalytics = "G-T1D8VD7D71"
enableRobotsTXT = true

[permalinks]
page = "/:slug/"
post = "/:year/:slug/"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100

[menu.main.params]
icon = "home"
newTab = "flase"

[[menu.social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/LoveSnowEx"

[menu.social.params]
icon = "brand-github"

# [[menu.social]]
# identifier = "twitter"
# name = "Twitter"
# url = "https://twitter.com"

# [menu.social.params]
# icon = "brand-twitter"

[related]
includeNewer = true
threshold = 60
toLower = false

[[related.indices]]
name = "tags"
weight = 100

[[related.indices]]
name = "categories"
weight = 200

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[markup.highlight]
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = false
style = "monokai"
tabWidth = 4

[sitemap]
  changefreq = "always"
  filename = "sitemap.xml"
  priority = 0.5
