version: "3.7"

services:
  caddy:
    image: caddy:2.7-alpine
    container_name: blog-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/public:/srv
